version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 1000
      runas: ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
