import Head from "next/head";
import { ApolloProvider } from "@apollo/client";
import client from "@/apollo/client";
import "../styles/sass/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }) {
  return (
    <ApolloProvider client={client}>
      <Head>
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ApolloProvider>
  );
}
